# .github/dependabot.yml
version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/" # Root directory
    schedule:
      interval: "daily" # "weekly" "monthly" if you want less frequent reminders