# .github/dependabot.yml
version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/" # Root directory
    schedule:
      interval: "weekly"
    allow:
      - dependency-type: "all"
        update-types:
          - "version-update:semver-minor"
          - "version-update:semver-patch"